language: python

python:
  - "3.5"
  - "3.6"

# TODO: remove these overrides once default dist supports python 3.7
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - "pip install astroid==2.0.0 cryptography pysftp>=0.2.9 botocore flake8 httplib2 mock psycopg2 pylint==2.2.2 pytest python-dateutil python-snappy python-systemd requests azure-storage"

script:
  - "make pylint"
  - "make flake8"
  - "make unittest"

addons:
  apt:
    packages:
      - libsnappy-dev
      - postgresql-9.4
